require('dotenv').config();
const mongoose = require('mongoose');

async function migrate() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI is not set in environment variables.');
    process.exit(1);
  }

  console.log('Connecting to MongoDB...');
  await mongoose.connect(uri);
  console.log('Connected.');

  try {
    const db = mongoose.connection.db;
    const collection = db.collection('messages');
    
    // Fetch all existing indexes on the 'messages' collection
    const indexes = await collection.indexes();
    console.log('Existing indexes on messages collection:');
    indexes.forEach(idx => console.log(` - ${idx.name}`));

    // The default name generated by Mongoose for { createdAt: 1 } is 'createdAt_1'
    const oldTtlIndexName = 'createdAt_1';
    
    const hasOldIndex = indexes.some(idx => idx.name === oldTtlIndexName);

    if (hasOldIndex) {
      console.log(`Found old TTL index '${oldTtlIndexName}'. Dropping it...`);
      await collection.dropIndex(oldTtlIndexName);
      console.log('Index dropped successfully.');
    } else {
      console.log(`Index '${oldTtlIndexName}' not found. It may have already been dropped.`);
    }

    console.log('\nMigration complete. The new Mongoose schema will automatically create the new indexes on the next app start (if autoIndex is enabled) or you can rely on Mongoose to build them in the background.');

  } catch (error) {
    console.error('Migration failed:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB.');
    process.exit(0);
  }
}

migrate();
